swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }

# swiftmailer:
#     transport:        gmail
#     username:         '%env(EMAIL_CARO)%'
#     password:         '%env(MDP_CARO)%'
#     host:             localhost
#     port:             465
#     encryption:       ssl
#     auth-mode:        login
#     spool: { type: 'memory' }
#     stream_options:
#         ssl:
#             allow_self_signed: true
#             verify_peer: false
#             verify_peer_name: false