vich_uploader:
    db_driver: orm

    mappings:
      property_image:
          uri_prefix: /images/shelters
          upload_destination: '%kernel.project_dir%/public/images/shelters'

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
